[project]
name = "python"
version = "0.1.0"
description = "Standard setup for Python projects using uv"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "uv",
    "pytest>=8.3.4",
]

[tool.pytest.ini_options]
pythonpath = "src"